In [4]:
import numpy as np

In [5]:
# 
# manual assigning value
numbers0 = np.array([2,4,5,6,11])
# using list comprehension
numbers = np.array([x for x in range(20) if x%2 == 0 ])
print(type(numbers))
print(numbers)
print(numbers.size)
print(numbers.ndim)
print(numbers.shape)
numbers


<class 'numpy.ndarray'>
[ 0  2  4  6  8 10 12 14 16 18]
10
1
(10,)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# multidimesional array
integers = np.array([[4,11,12],[5,12,13]])
print(integers)

print('Size: ', integers.size)
print('Item Size: ', integers.itemsize)
print('Dimensions: ', integers.ndim)
print('Shape: ', integers.shape)

[[ 4 11 12]
 [ 5 12 13]]
Size:  6
Item Size:  8
Dimensions:  2
Shape:  (2, 3)


In [11]:
# Float array
float = np.array([0.1,0.2,0.3])
print(float)

print('Size: ', float.size)
print('Item Size: ', float.itemsize)
print('Dimensions: ', float.ndim)
print('Shape: ', float.shape)

[0.1 0.2 0.3]
Size:  3
Item Size:  8
Dimensions:  1
Shape:  (3,)


In [12]:
# iteration through the arrays
for row in integers:
    for column in row:
        print(column, end=' ')
    print()
    
# using flat
for row in integers.flat:
    print(row,end=' ')
    

4 11 12 
5 12 13 
4 11 12 5 12 13 

In [13]:
# 
zeros = np.zeros((4,5))
zeros1 = np.zeros((4,5), dtype='int')
ones = np.ones((4,5))
fives = np.full((4,5),5)
fives1 = np.full((4,5),5, dtype='int')
# do check with dtype argument, default is float

print("zeros")
print(zeros)
print(zeros.shape)

print("zeros")
print(zeros1)
print(zeros1.shape)

print("fives")
print(fives)
print(fives.shape)

print("fives1")
print(fives1)
print(fives1.shape)

zeros
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(4, 5)
zeros
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(4, 5)
fives
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
(4, 5)
fives1
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
(4, 5)


In [19]:
# range function
ranged_arrays = np.arange(1,11).reshape(5,2)
print(ranged_arrays)

listed_arrays = np.array([x for x in range (10 , 1, -2)])
print(listed_arrays)

listed_arrays.reshape(1,5)
print(listed_arrays)

float_ranges = np.linspace(0.0,1.0, num = 30)
print(float_ranges)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[10  8  6  4  2]
[10  8  6  4  2]
[0.         0.03448276 0.06896552 0.10344828 0.13793103 0.17241379
 0.20689655 0.24137931 0.27586207 0.31034483 0.34482759 0.37931034
 0.4137931  0.44827586 0.48275862 0.51724138 0.55172414 0.5862069
 0.62068966 0.65517241 0.68965517 0.72413793 0.75862069 0.79310345
 0.82758621 0.86206897 0.89655172 0.93103448 0.96551724 1.        ]


In [20]:
# bit of performance
%timeit sum([x for x in range(10_000_000)])

413 ms ± 1.94 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
%timeit np.arange(10_000_000).sum()

18.6 ms ± 659 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
# arithamatic operators
print(integers)
print(integers * 2)
print(integers ** 3)
print(integers + 10)

print(numbers)
# print(float_ranges * numbers)
temp = numbers > 12
print('temp=',temp)
# mask to filter values
print(numbers[numbers > 5])

[[ 4 11 12]
 [ 5 12 13]]
[[ 8 22 24]
 [10 24 26]]
[[  64 1331 1728]
 [ 125 1728 2197]]
[[14 21 22]
 [15 22 23]]
[ 0  2  4  6  8 10 12 14 16 18]
temp= [False False False False False False False  True  True  True]
[ 6  8 10 12 14 16 18]


In [24]:
#  activity

values = np.arange(1,6)**2
print(values)

[ 1  4  9 16 25]


In [36]:
grades = np.array([[87,96, 70], [80,85,75], [94,77,90], [100,81,82]])
print(grades)
#grades.var()
print(grades.min())
grades.min(axis=1)

[[ 87  96  70]
 [ 80  85  75]
 [ 94  77  90]
 [100  81  82]]
70


array([70, 75, 77, 81])

In [37]:

# random numbers
random = np.random.randint(5,20,15)
print(random)

# generating the courses marks for 6 courses for 5 students
grades = np.random.randint(40,100,30).reshape(5,6)
print(grades)

[12  8 19 15  5 19  6 14 15 11  5 17  5 17 13]
[[84 43 85 43 92 90]
 [76 88 71 95 66 61]
 [49 78 74 84 49 88]
 [73 91 90 49 76 53]
 [47 86 84 56 51 68]]


In [38]:
# indexing
print(grades[2,2])  #3rd student k 3rd marks
# slicers => rows
print(grades[1]) #2ns student k saray marks
# sequential row picks
print(grades[1:4]) # row 1 sa row 3
# row 0,2,3
print(grades[[0,2,3]])

# sequential coulmn picks
# all rows of specific column
print(grades[:,0])#sirf pehla column

print(grades[:,2:4])#sari rows 2 and 3 column 
print(grades[:,[0,2,4]])


74
[76 88 71 95 66 61]
[[76 88 71 95 66 61]
 [49 78 74 84 49 88]
 [73 91 90 49 76 53]]
[[84 43 85 43 92 90]
 [49 78 74 84 49 88]
 [73 91 90 49 76 53]]
[84 76 49 73 47]
[[85 43]
 [71 95]
 [74 84]
 [90 49]
 [84 56]]
[[84 85 92]
 [76 71 66]
 [49 74 49]
 [73 90 76]
 [47 84 51]]


In [42]:
marks = np.random.randint(40,100,60).reshape(10,6)
print(marks)

print('average student wise = ', marks.mean(axis=1))
print('average course wise = ', marks.mean(axis=0))

print('Max student wise = ', marks.max(axis=1))
print('Max course wise = ', marks.max(axis=0))

print('Average of top performing student = ', marks.mean(axis=1).max())

print('alternating students = ', marks[[x for x in range(10) if x%2==0]]) # or marks[0:10:2]
print('alternating courses = ', marks[:,0:6:2])

[[58 97 63 58 46 80]
 [61 77 83 52 60 53]
 [57 93 54 52 40 67]
 [41 68 81 44 94 87]
 [72 56 89 45 92 75]
 [80 85 70 78 80 57]
 [42 73 94 64 45 74]
 [85 96 72 89 61 92]
 [98 66 78 82 63 92]
 [97 91 76 82 69 73]]
average student wise =  [67.         64.33333333 60.5        69.16666667 71.5        75.
 65.33333333 82.5        79.83333333 81.33333333]
average course wise =  [69.1 80.2 76.  64.6 65.  75. ]
Max student wise =  [97 83 93 94 92 85 94 96 98 97]
Max course wise =  [98 97 94 89 94 92]
Average of top performing student =  82.5
alternating students =  [[58 97 63 58 46 80]
 [57 93 54 52 40 67]
 [72 56 89 45 92 75]
 [42 73 94 64 45 74]
 [98 66 78 82 63 92]]
alternating courses =  [[58 63 46]
 [61 83 60]
 [57 54 40]
 [41 81 94]
 [72 89 92]
 [80 70 80]
 [42 94 45]
 [85 72 61]
 [98 78 63]
 [97 76 69]]


In [45]:
# single dimension vector flatten vs ravel
flattened = grades.flatten()
print(flattened)
flattened = grades.ravel()
print(flattened)

[84 43 85 43 92 90 76 88 71 95 66 61 49 78 74 84 49 88 73 91 90 49 76 53
 47 86 84 56 51 68]
[84 43 85 43 92 90 76 88 71 95 66 61 49 78 74 84 49 88 73 91 90 49 76 53
 47 86 84 56 51 68]


In [48]:
import pandas as pd

# grades = pd.Series([90,91,85])
grades = pd.Series([90,91,85], index = ['Zero','One','Two'])
print(grades)
print(grades.describe())

grades = pd.Series({"Zer0":90, "One":91, "Two":85})
print(grades)
print(grades.describe())

Zero    90
One     91
Two     85
dtype: int64
count     3.000000
mean     88.666667
std       3.214550
min      85.000000
25%      87.500000
50%      90.000000
75%      90.500000
max      91.000000
dtype: float64
Zer0    90
One     91
Two     85
dtype: int64
count     3.000000
mean     88.666667
std       3.214550
min      85.000000
25%      87.500000
50%      90.000000
75%      90.500000
max      91.000000
dtype: float64
